### ISSUE TITLE
usage of command palette

### ISSUE THREAD

**Issue by kschaper** [atom/flight-manual.atom.io#18]
I noticed that the usage of the command palette is not described correctly. Examples:

`/getting-started-atom-basics`
"To open the Settings screen ... You can also search for settings-view:open"
Here one should enter something like "settingsviewopen"

`/getting-started-atom-basics`
"... the tree-view:toggle command from the Palette ..."
One should enter "treeto" for example.

**Comment by izuzak** [comment]
Yeah, I agree -- the docs list the non-humanized command `tree-view:toggle`, but you can't copy-paste that into the Command Palette finder because it uses the humanized version: `Tree View: Toggle`. 

Definitely worth fixing/clarifying. :+1: I've already done that in [one of the sections](https://github.com/atom/docs/commit/e0036b9435fc32709f08748937718033c92a9eef) recently, by just replacing the non-humanized command with the humanized version.

**Comment by lee-dohm** [comment]
Between changes in the content and the fuzz-aldrin-plus package, this has been fixed.
