### ISSUE TITLE
Computer octicon still showing in platform-nav when there is no platform-specific content

### ISSUE THREAD

**Issue by lee-dohm** [atom/flight-manual.atom.io#264]
See: http://flight-manual.atom.io/resources/sections/glossary/

<img width="372" alt="screen shot 2016-09-04 at 10 33 11 am" src="https://cloud.githubusercontent.com/assets/1038121/18232725/00e2f7e4-728b-11e6-9ef0-1ca253fc943d.png">

I suspect this was introduced with #250.

@simurai can you take a look?

**Comment by simurai** [comment]
I think the problem is that the `show` class gets added because there are `platform-all` keybindings on that page, but none platform specific.

![screen shot 2016-09-10 at 11 29 38 pm](https://cloud.githubusercontent.com/assets/378023/18411354/c8335526-77b0-11e6-8dba-15de5777ff00.png)

`if (platformSpecificSectionsCount > 0) {` ([code](https://github.com/atom/flight-manual.atom.io/blob/master/assets/javascripts/platform-nav.js#L72)) passes with `1` because `all` is part of the [validPlatforms](https://github.com/atom/flight-manual.atom.io/blob/master/assets/javascripts/platform-nav.js#L19). If I remove `all`, it works. But not sure if that is needed for something else.

**Comment by lee-dohm** [comment]
Thanks for tracking that down. I'll take a look tomorrow.
