### ISSUE TITLE
One Flight Manual Example Uses JavaScript

### ISSUE THREAD

**Issue by RobertBColton** [atom/flight-manual.atom.io#350]
As far as I understand, all of the docs should be in Coffeescript? I had a bit of a hard time reading this one document because I am not as familiar yet with Coffeescript.
http://flight-manual.atom.io/hacking-atom/sections/package-active-editor-info/#platform-windows

I think consistency of using all the same language across all the docs would be the best, but an alternative may be to do what the Microsoft Docs do and provide a version in both languages at the same time. It seems the docs already designed this way to handle differences between WIndows, Linux, and Mac.

**Comment by lee-dohm** [comment]
Historically all of our examples have been in CoffeeScript, but we don't have a requirement for it. Since more of Atom is being written in JavaScript, we have discussed offering a toggle like you mention. I would prefer it if it would automatically translate between the two so that we don't have to maintain two separate chunks of identical code. I don't have any ETA of when something like that might happen though.

**Comment by RobertBColton** [comment]
Sounds good! Just for reference, I found http://js2.coffee/ to be pretty useful and it does basically what you described (transpiling the CS to JS). I ended up going with JavaScript for developing my package in the end though.
