### ISSUE TITLE
Help me out, or is better to fight Dragons alone?

### ISSUE THREAD

**Issue by BigGuy573** [atom/flight-manual.atom.io#525]
V175, V176, V176 software version: #02#*

 C168, W220 software version: *#**837#

 C138, C139, C140 software version: #02#*

 C113, C114, C115, C115i, C116, C117, C118 software version: #02#*

 C257, C261 software version: #02#*

 V171, V172, V173 software version: #02#*

 C155, C156, C157 software version: #02#*

 W208, W375 software version: #02#*

 and yes

**Comment by BigGuy573** [comment]
Thanks.  BigGuy573

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
