### ISSUE TITLE
Next and Previous button in Flight Manual.

### ISSUE THREAD

**Issue by yuvi17** [atom/flight-manual.atom.io#544]
## Summary

For someone reading the Atom Flight Manual, there should be buttons to go to previous and next topic in the documentation. This will lead to better User Experience (and less scrolling to the top every time)

## Motivation
The motivation for this came as I was reading the documentation and had to scroll up a countless number of times to get to the top of the page, and then select the next article there. This gets a bit irritating after the first few times. Adding a next and previous button would help people reading the whole documentation navigating the flight manual in a better manner. This is not good user experience.

## Describe alternatives you've considered

The only alternative is to scroll up and click on next. Something that is not very intuitive.

## Attached Screenshot.
![image](https://user-images.githubusercontent.com/12815046/60464295-c01bec80-9c6b-11e9-9a50-350785f6b3c4.png)

There is a similar issue with a few comments but no conclusion [here.](https://github.com/atom/flight-manual.atom.io/issues/216) from ~3 years ago.

**Comment by rsese** [comment]
Thanks for the suggestion!

> There is a similar issue with a few comments but no conclusion here. from ~3 years ago.

Though the issue hasn't been resolved/closed/etc. it's still open so we'll close in favor of that issue and I'll mention this to the other maintainers to see if there's any additional thoughts to share.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
